# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 043b28966817fb06cb41dece9f20a59b06af673978d5299b6042e0049263bb4fd87dd17249481141100345e312d1ddba7a2cd49fec3c1cc1cebe23297081f9fe

test:
  secret_key_base: 37c9b0f40ef3a10de0d8e1a67d84d77fbc88ac4c922b15067c14a285972880960e9593a3cc2291e0cc717cca7a4736d127678b41d5605dad9cfdf2fb5d5fa8df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
